/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pkg1306180132_vizeproject;

import java.io.IOException;
import static java.lang.Double.sum;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
 
/**
 *
 * @author moayy
 */
public class MusteriIslemleri extends javax.swing.JFrame {

    /**
     * Creates new form IslemlerGUI
     */
    public MusteriIslemleri() throws IOException {
        initComponents();
         Database.saveData();
         Database.loadData();
     //   showDataBaseOfEmploye ob1=new showDataBaseOfEmploye(); 
    }

    
    public String checkBakiye(String Ad,String Soyad,String Sifre)
    {
         for(int i=0 ; i<Database.veriMusteri.size(); i++)
        {
            if(Database.veriMusteri.elementAt(i).Ad.equals(Ad)&&
            Database.veriMusteri.elementAt(i).Soyad.equals(Soyad)&&        
            Database.veriMusteri.elementAt(i).Sifre.equals(Sifre))        
            {
                return Database.veriMusteri.elementAt(i).bakiye.toString(); 
            }
        }
      
        return "0";
    }
    
    // this funtion is used for pulling and pushing money for cutormer's balance
     public String paraYatirma_cekme(String Ad,String Soyad,String Sifre,String addMoney,String subMoney)
    {
        if(!subMoney.equals(""))// here is to subtract money
        {
             for(int i=0 ; i<Database.veriMusteri.size(); i++)
        {
            if(Database.veriMusteri.elementAt(i).Ad.equals(Ad)&&
            Database.veriMusteri.elementAt(i).Soyad.equals(Soyad)&&        
            Database.veriMusteri.elementAt(i).Sifre.equals(Sifre))        
            {
                double amount=Double.parseDouble(Database.veriMusteri.elementAt(i).bakiye)
                       - Double.parseDouble(subMoney); 
                if(amount>0)
                {
                    Database.veriMusteri.elementAt(i).bakiye=Double.toString(amount);
                return Database.veriMusteri.elementAt(i).bakiye; 
                }
                else 
                    return "-1"; 
            }
        }
        }
        else  // this is to add money 
         for(int i=0 ; i<Database.veriMusteri.size(); i++)
        {
            if(Database.veriMusteri.elementAt(i).Ad.equals(Ad)&&
            Database.veriMusteri.elementAt(i).Soyad.equals(Soyad)&&        
            Database.veriMusteri.elementAt(i).Sifre.equals(Sifre))        
            {
                double amount=Double.parseDouble(Database.veriMusteri.elementAt(i).bakiye)
                       + Double.parseDouble(addMoney); 
                 Database.veriMusteri.elementAt(i).bakiye=Double.toString(amount);
                return Database.veriMusteri.elementAt(i).bakiye; 
            }
        }
      
        return "0";
    }
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jButton7 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setText("Para Yatirma");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton2.setText("Para Cekme");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton3.setText("Bakiye Ogrenme ");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setBackground(new java.awt.Color(255, 255, 255));
        jButton4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton4.setText("Fatura Ödeme");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton5.setText("Para Transfer");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton6.setText("Kredi tableb verme ");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pkg1306180132_vizeproject/I am a button.png"))); // NOI18N

        jButton7.setBackground(new java.awt.Color(102, 102, 255));
        jButton7.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButton7.setText("Geri Dönme");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(68, 68, 68)
                            .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jButton1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jButton4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 167, Short.MAX_VALUE)
                        .addComponent(jButton5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(17, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(268, 268, 268))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(68, 68, 68)
                        .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(66, 66, 66)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(53, 53, 53)
                .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
  if(evt.getSource()==jButton1)
  {
        String addedAmountmoney = JOptionPane.showInputDialog("paraniz miktarini girin");
        String newBakiye=paraYatirma_cekme(EntranceOfMusteri.Ad,EntranceOfMusteri.Soyad,
                EntranceOfMusteri.Sifre,addedAmountmoney,"");
        EntranceOfMusteri.Bakiye=newBakiye; 
        double eskiBakiye=Double.valueOf(newBakiye)-Double.valueOf(addedAmountmoney); 
        JOptionPane.showMessageDialog(null," Eski bakiyi             ="+eskiBakiye +
                        "\n Gidiginiz miktari   ="+addedAmountmoney+
                        "\n Simdilik Bakiyi     ="+newBakiye, "BayikeOgrenme", JOptionPane.PLAIN_MESSAGE);
      try {
           Database.saveData();
           Database.loadData();
           showDataBaseOfCustomer ob=new showDataBaseOfCustomer(); 
      } catch (IOException ex) {
          Logger.getLogger(MusteriIslemleri.class.getName()).log(Level.SEVERE, null, ex);
      }
      
        
  }
      
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        
        EntranceOfMusteri ob = null; 
        
         this.setVisible(false);
       
        try {
            Database.saveData();
            Database.loadData();
             ob = new EntranceOfMusteri();
        } catch (IOException ex) {
            Logger.getLogger(MusteriIslemleri.class.getName()).log(Level.SEVERE, null, ex);
        }
         
    
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
      if(evt.getSource()==jButton2)
       {
              String subMoney = JOptionPane.showInputDialog("Ne kadar para çekmek istiyorsunuz?");
         String subtractedBakiye = paraYatirma_cekme(EntranceOfMusteri.Ad, EntranceOfMusteri.Soyad
                 ,EntranceOfMusteri.Sifre, "",subMoney);
         if(subtractedBakiye.equals("-1"))
         {
             JOptionPane.showMessageDialog(null, "Girdiğiniz miktarı bakiyenizdan cekılmez\n Para az", "Uyari", JOptionPane.PLAIN_MESSAGE);
         }
         else 
           {
             double eskiBakiye =Double.valueOf(subMoney)+Double.valueOf(subtractedBakiye); 
                JOptionPane.showMessageDialog(null," Eski bakiyi             ="+eskiBakiye+
                        "\n aldiginiz miktari   ="+subMoney+
                        "\n Simdilik Bakiyi     ="+subtractedBakiye, "BayikeOgrenme", JOptionPane.PLAIN_MESSAGE); 
                  try {
                      Database.saveData();
                       Database.loadData();
                showDataBaseOfCustomer ob=new showDataBaseOfCustomer(); 
                  } catch (IOException ex) {
                      Logger.getLogger(MusteriIslemleri.class.getName()).log(Level.SEVERE, null, ex);
                  }
               
           }
       }
           
    }//GEN-LAST:event_jButton2ActionPerformed
    
    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        if(evt.getSource()==jButton3)
        {
             String bakiye=checkBakiye(EntranceOfMusteri.Ad,EntranceOfMusteri.Soyad,EntranceOfMusteri.Sifre);
        
        JOptionPane.showMessageDialog(null, "Bakiyeniz =  "+bakiye, "BayikeOgrenme", JOptionPane.PLAIN_MESSAGE);
        }
       
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        FaturaOdeme ob=null;
        try {
            ob = new FaturaOdeme();
        } catch (IOException ex) {
            Logger.getLogger(MusteriIslemleri.class.getName()).log(Level.SEVERE, null, ex);
        }
        ob.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        if(evt.getSource()==jButton5)
        {
        paraTransfer ob; 
            try {
                ob = new paraTransfer();
                 ob.setVisible(true);
        this.setVisible(false);
            } catch (IOException ex) {
                Logger.getLogger(MusteriIslemleri.class.getName()).log(Level.SEVERE, null, ex);
            }
        
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        try {
            // TODO add your handling code here:
            PersonelIslemleri ob=new PersonelIslemleri(EntranceOfMusteri.Bakiye);
            Database.saveData();
            Database.loadData();
        } catch (IOException ex) {
            Logger.getLogger(MusteriIslemleri.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_jButton6ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MusteriIslemleri.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MusteriIslemleri.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MusteriIslemleri.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MusteriIslemleri.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new MusteriIslemleri().setVisible(true);
                } catch (IOException ex) {
                    Logger.getLogger(MusteriIslemleri.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
