/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pkg1306180132_vizeproject;

import java.io.FileNotFoundException;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author moayy
 */
public class paraTransfer extends javax.swing.JFrame {

    /**
     * Creates new form sendingMoneyToOtherPerson
     */
    public paraTransfer() throws IOException {
        initComponents();
        Database.saveData();
        Database.loadData();
    }

    public int sendingMoneyToOtherPerson(String Ad, String Soyad, String Eposta, String gonderilenMiktar) throws FileNotFoundException, IOException {

        boolean found = false;
        for (int i = 0; i < Database.veriMusteri.size(); i++) {
            // to check wehter the customer is existed or not 
            if (Database.veriMusteri.elementAt(i).Ad.equals(Ad)
                    && Database.veriMusteri.elementAt(i).Soyad.equals(Soyad)
                    && Database.veriMusteri.elementAt(i).Eposta.equals(Eposta)) {

                double result = Double.parseDouble(EntranceOfMusteri.Bakiye);
                double output = result - Double.parseDouble(gonderilenMiktar);
                if (result > 0 && output > 0) {
                    found = true;
                    String eskiBakiye = Database.veriMusteri.elementAt(i).bakiye;
                    String newBakiye = Double.toString(Double.parseDouble(eskiBakiye)
                            + Double.parseDouble(gonderilenMiktar));
                    // here is the adding of money to new account 
                    Database.veriMusteri.elementAt(i).bakiye = newBakiye;

                    JOptionPane.showMessageDialog(null, "Done Successfully\n");

                    JOptionPane.showMessageDialog(null, "Alici kisi     " + Ad + "  " + Soyad
                            + "\n  Eski Bakiye = " + eskiBakiye
                            + "\n  YeniBakiye   =  " + newBakiye,
                             "OUTPUT", JOptionPane.PLAIN_MESSAGE);
                } else {
                    return 2;
                }

            }
        }

        // here to modify the data of sending person ( to subtract data from the sent person)
        if (found) {
            for (int i = 0; i < Database.veriMusteri.size(); i++) {
                if ((Database.veriMusteri.elementAt(i).Ad).equals(EntranceOfMusteri.Ad)
                        && (Database.veriMusteri.elementAt(i).Soyad).equals(EntranceOfMusteri.Soyad)
                        && (Database.veriMusteri.elementAt(i).Sifre).equals(EntranceOfMusteri.Sifre)) {
                    double result = Double.parseDouble(Database.veriMusteri.elementAt(i).bakiye);
                    Database.veriMusteri.elementAt(i).bakiye = Double.toString(result - Double.parseDouble(gonderilenMiktar));

                    JOptionPane.showMessageDialog(null, "Gonderen kisi     " + EntranceOfMusteri.Ad + "  "
                            + "\n    Eski Bakiye =" + result
                            + "\n    Yeni Bakiye =" + Database.veriMusteri.elementAt(i).bakiye);
                    return 1;
                }

            }
        }
        return 0;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setBackground(new java.awt.Color(0, 153, 51));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setText("Gönder");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 400, -1, -1));

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 200, 192, -1));

        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 240, 192, -1));
        getContentPane().add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 280, 192, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 153, 0));
        jLabel1.setText("Alici Adi");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 153, 51));
        jLabel3.setText("Eposta");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 153, 0));
        jLabel2.setText("Alici Soyadi");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, -1, 20));

        jButton2.setBackground(new java.awt.Color(0, 153, 51));
        jButton2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton2.setText("Iptal Et");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 400, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 153, 51));
        jLabel5.setText("Gonderilen Miktari");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 340, -1, -1));
        getContentPane().add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 330, 190, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pkg1306180132_vizeproject/natuer.jpg"))); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 790, 560));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        if (evt.getSource() == jButton1) {
            String Ad = jTextField1.getText().toString();
            String Soyad = jTextField2.getText().toString();
            String Eposta = jTextField3.getText().toString();
            String GonderMiktari = jTextField4.getText().toString();
            try {
                // here to sendingMoneyToOtherPerson input and change the file itself

                int result = sendingMoneyToOtherPerson(Ad, Soyad, Eposta, GonderMiktari);

                switch (result) {
                    case 0: {
                        JOptionPane.showMessageDialog(null, "Bilgiler esleslenmedi", "OUTPUT", JOptionPane.PLAIN_MESSAGE);
                        break;
                    }
                    case 1: {
                        // show the loginGUI again 
                        MusteriIslemleri e = new MusteriIslemleri();
                        e.setVisible(true);
                        this.setVisible(false);
                        showDataBaseOfCustomer ob = new showDataBaseOfCustomer();

                        break;
                    }
                    case 2: {
                        JOptionPane.showMessageDialog(null, "Girdigin miktari bakiyenizden daha buyuk", "OUTPUT", JOptionPane.PLAIN_MESSAGE);
                        break;
                    }

                }

            } catch (IOException ex) {
                Logger.getLogger(changePassWordGUI.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        if (evt.getSource() == jButton2) {
            MusteriIslemleri ob = null;
            try {
                ob = new MusteriIslemleri();
            } catch (IOException ex) {
                Logger.getLogger(paraTransfer.class.getName()).log(Level.SEVERE, null, ex);
            }
            this.setVisible(false);
            ob.setVisible(true);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(paraTransfer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(paraTransfer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(paraTransfer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(paraTransfer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new paraTransfer().setVisible(true);
                } catch (IOException ex) {
                    Logger.getLogger(paraTransfer.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    // End of variables declaration//GEN-END:variables
}
